import { CompletionProvider } from "./completionProvider";
import { DefaultSetting } from "./defaultSetting";
import { Formatter } from "./formatter";
import { HoverProvider } from "./hoverProvider";
import { LanguageService } from "./languageService";
import { ResourcesProviderBase } from "./resourcesProviderBase";
import { Setting } from "./setting";
import { Validator } from "./validator";
declare const descriptions: any;
declare const dictionary: any;
declare const snippets: any;
export { DefaultSetting, Formatter, HoverProvider, LanguageService, CompletionProvider, ResourcesProviderBase, Setting, Validator, descriptions, dictionary, snippets };
